services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.1-alpine
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - internal_net
  

networks:
  internal_net:
    name: intnet
    driver: bridge