services:
  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - internal_net
  mqtt-bluebird:
    container_name: mqtt-bluebird
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    networks:
      - internal_net
  
  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    restart: unless-stopped
    ports:
      - "4000:4000"  # Puerto web para acceder a MQTT Explorer
    networks:
      - internal_net
    environment:
      - HTTP_PORT=4000
      - HTTP_USER=admin        # Usuario para acceso web (opcional)
      - HTTP_PASSWORD=admin    # Contraseña para acceso web (opcional)

  node:
    container_name: nodePublisher
    build: 
      context: ./nodeContainer
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      - internal_net
networks:
  internal_net:
    name: intnet
    driver: bridge