FROM eclipse-mosquitto:2.1.2-alpine
COPY ./mosquitto.conf /mosquitto/config/mosquitto.conf
#RUN mosquitto_passwd -b -c /mosquitto/config/passwd test test && \
#    chown mosquitto:mosquitto /mosquitto/config/passwd && \
#    chmod 0600 /mosquitto/config/passwd